### ISSUE TITLE
Should we provide a way to delete a masthead/thumbnail images?

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#1034]
May be complicated to go back to the default generated thumbnail but it may be useful in some cases.  Not sure...

**Comment by ggeisler** [comment]
I considered this in the original designs but didn't see a real need for it, at least for the masthead, since we have the "Use image for masthead" checkbox. The curator could turn that checkbox off if they don't want the masthead image used.

For the thumbnail, I guess I could see a delete being useful as a quick way to get back to the original, default image we give them, but then again, they could always select that item on their own if they really want it (though they might not remember what it was -- but it was basically a random selection anyway).

I don't really see a strong enough case to provide a way to delete either the masthead or the thumbnail. And I worry that if there is a delete option, some curators might think they have to delete a current one before selecting a new one, which would add a step to the process of changing images. 

Let me know if you can think of any scenarios that suggest a stronger need for this than I'm thinking of.

**Comment by cbeer** [comment]
I think we resolved to close this, yeah?

**Comment by ggeisler** [comment]
Yep.
