### ISSUE TITLE
Improved background job processing notifications

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/spotlight#1220]
Now that reindexing is able to use background jobs for all indexing, we need better in-application reporting for status, progress, and errors.

**Comment by ggeisler** [comment]
I suggest we show a status panel on the Curation > Items page whenever the exhibit curator has selected either the "Reindex items" or "Add repo/non-rep items" action.

This panel would be shown on the page anytime the page is displayed while there is an indexing background job running, and remains on the page after a job has completed (but would not be shown if the user navigates away from the page and then redisplays it and there are no indexing jobs then running).

The panel shows:

- Date and time of the start of the job, the type of job, and the total number of items to be processed
- Date and time of the last update, action taking place, and the number of the total number of items that have been processed
- A progress bar that is just the percentage of items completed of the total number of items

![curation_-_curation_-_items___exhibit_one_-_blacklight](https://cloud.githubusercontent.com/assets/101482/11381108/0106a142-92af-11e5-92c9-5e96498da1b8.png)

The type of job can either be "Reindexing" as in the mockup or, if the user selected either of the "Add repository item" or "Add non-repository item" actions, "Add items." So if the background job was initiated by one of the add items actions:

- panel title should be: "Add items status"
- start of job message: "Began adding a total of xx items"
- last update message: Added xx of xx items"

(I understand that most of the work of the background job does when adding items is actually indexing, but from the curator point-of-view, I suggest it makes more sense to refer to the job at the more general level of adding items, since that's the action they choose to perform.)

As long as the Items page is displayed, we would use ajax to update the status of the page, which would just update the last update message and the progress bar.

If when checking for the current status we discover that an error has occurred with the job, we should present a simple error message instead of the progress bar, like this:

![curation_-_curation_-_items___exhibit_one_-_blacklight 2](https://cloud.githubusercontent.com/assets/101482/11381658/1f26c140-92b2-11e5-94ec-8806c04a6bd3.png)

**Comment by ggeisler** [comment]
In case it's helpful...

### HTML
````html
<div class="panel panel-info index-status">
  <div class="panel-heading">
    <h3 class="panel-title">Reindexing status</h3>
  </div>
  <div class="panel-body">
    <p>
      <span class="text-muted">2015-11-24 at 10:53 am:</span> Began reindexing a total of 55 items.
    </p>
    <p>
      <span class="text-muted">2015-11-24 at 11:04 am:</span> Reindexed 32 of 55 items.
    </p>

    <p class="bg-warning">An error occured while reindexing. Contact your exhibits administrator for more information.</p>

    <div class="progress">
      <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="58" aria-valuemin="0" aria-valuemax="100" style="width: 58%">58%
        <span class="sr-only">Reindexing 58% complete</span>
      </div>
    </div>
  </div> 
</div>
````

### SCSS

````scss
.index-status {
  margin-bottom: $padding-large-vertical * 2
}
````
