### ISSUE TITLE
Layout of Embed + Text widget

### ISSUE THREAD

**Issue by snydman** [sul-dlss/spotlight#782]
Adding a purl to embed works great.  But when text is added to the widget the layout (percentages) is off.

**Comment by ggeisler** [comment]
I noticed that the widget block that is added to the page for this has a class of `item-text` (even though this is not an item + text widget) so I wonder if that is intentional (or maybe we are just reusing the item-text class for common styling? If not intentional, that might be a source of the display issue. In any event, I think the Embed + Text widget should be displayed similar to how it is displayed on the Item record page, namely the embed portion gets 50% width and the text portion gets 50% width.

Here's a homepage with the Embed + Text widget at 50% width for each of the block and text pieces, plus `padding-right: $padding-large-horizontal;` for the text piece (though that would be `padding-left` if the curator choose to put the text on the right), and a clearfix added between it and the Item + Text widget I added below it:

#### Desktop sizes

![desktop-sizes](https://cloud.githubusercontent.com/assets/101482/6539456/480019f2-c429-11e4-896c-53e5fbf29f3b.png)
----

#### Without a sidebar

![no-sidebar](https://cloud.githubusercontent.com/assets/101482/6539457/5444e9b8-c429-11e4-8467-24a5727ddb64.png)
----

#### Mobile sizes

I think the 50% split between the embed and the text is still fine at small viewport width, but at `$screen-xs-max` we should make the two pieces 100%, similar to how the embed works at `$screen-sm-max` on the Item record page:

![xs-viewport](https://cloud.githubusercontent.com/assets/101482/6539482/e84a2236-c429-11e4-9746-3183355fa858.png)
