### ISSUE TITLE
grouping function

### ISSUE THREAD

**Issue by whisere** [sul-dlss/spotlight#837]
Is it possible to have the same grouping function like the one in solritas/solr with spotlight? Thanks

**Comment by jkeck** [comment]
@whisere I'm not super familiar with solritas so I'm totally naive about anything special that solritas may be doing.

Blacklight itself has a simple grouping implementation that you can see at https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/solr_response/group.rb and https://github.com/projectblacklight/blacklight/blob/master/spec/lib/blacklight/solr_response/group_spec.rb

Since that type of grouping is supported by Blacklight you should also be able to do in in Spotlight.

**Comment by whisere** [comment]
Thanks Jessie, I will try this.
