### ISSUE TITLE
Create derivatives from uploaded non-repo images

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#839]
This should be something that we make configurable by the implementing app (somehow, maybe through a proc or something), but we'll probably want defaults.

My initial thoughts are full (original), thumb (400px long-edge), and square (100x100?).

We also have a large version that we index into our fixtures but I'm not sure we use that anywhere or what the dimensions relative to the original are.

**Comment by ggeisler** [comment]
square = 100x100
thumb = 400px long-edge
full = original

Seem like the right default values to me. Making these configurable (at some point) makes sense since other institutions might have different local standard sizes.

I'm on the fence as to whether another size between thumb and full (large) would be useful. I don't see it being useful with the current state of Spotlight, but as we add more visually-oriented features for #786 it's possible there could be places where an image larger than 400px will called for and having to resort to the original size (e.g., a 3800px image) for that purpose would feel inefficient. At this point, though, I'm not sure there will be any compelling cases for larger than 400px so maybe we just stick with the three sizes you suggest. Seems like if we need to add a large size later it might not be too difficult to add?
