### ISSUE TITLE
Titles of non-repository items should be editable

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/spotlight#841]
The way we have things setup we are mapping the title that is submitted to the configured title field.  However; this isn't a field that the user can edit once they've uploaded the file.

I guess a related question would be if these objects should be delete-able from the UI.

**Comment by ggeisler** [comment]
Good questions. I think we do need to give the curator the ability to edit a non-repo item title. Since there could be other fields associated with the record that have been filled out (exhibit-specific fields or the future other non-repo item fields), it doesn't seem reasonable to force the curator to delete and re-add a non-repo item to fix a title problem and thereby lose work done to fill out the other metadata fields.

For non-repo items, could we make all fields editable along with the exhibit-specific fields and tag on the item record page, like this:

![maps_of_africa_-_blacklight](https://cloud.githubusercontent.com/assets/101482/5685721/f7a24416-97f1-11e4-8c36-c9d8765f991f.png)

(In this example, Display case and Exhibition note are exhibit-specific fields.) This is different behavior than for repo items where the form only includes the exhibit-specific fields and tags, but since the non-repo item metadata doesn't come from an authoritative source like repo items, it seems more likely that there will be occasions when a field needs fixed or updated.

I created #843 to address the deleteable question so we can debate that issue without impacting progress on this one.

**Comment by ggeisler** [comment]
When we add the other default non-repository fields (#787), they should also be editable, appearing after title in the form.
